// frontend/src/pages/Directory.tsx
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import type { LdapPerson, LdapResponse, Role } from '../types';
import { useToast } from '../context/ToastContext';
import { emitDataChanged } from '../lib/events';
import { Modal, Field, Empty, Avatar, SearchBox, TableSkeleton, ErrorState } from '../components/ui';
import { IconLdap, IconDownload, IconCheck, IconRefresh, IconServer } from '../components/icons';

export default function Directory() {
  const toast = useToast();
  const [data, setData] = useState<LdapResponse | null>(null);
  const [roles, setRoles] = useState<Role[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [q, setQ] = useState('');
  const [importing, setImporting] = useState<LdapPerson | null>(null);

  const load = async () => {
    setLoading(true); setError(null);
    try {
      const [d, r] = await Promise.all([api.ldapUsers(), api.listRoles()]);
      setData(d); setRoles(r);
    } catch (e) { setError((e as Error).message); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const people = (data?.people || []).filter((p) =>
    `${p.firstName} ${p.lastName} ${p.username} ${p.cargo} ${p.department}`.toLowerCase().includes(q.toLowerCase()));

  return (
    <>
      <div className="page-head">
        <div>
          <h1>Directorio LDAP</h1>
          <p>Origen exclusivo de los usuarios “cliente final”. Desde aquí se integran al sistema y se les pueden asignar roles.</p>
        </div>
        <button className="btn btn-ghost" onClick={load}><IconRefresh /> Actualizar</button>
      </div>

      {data && (
        <div className={`banner ${data.source === 'LDAP' ? 'banner-ok' : 'banner-warn'} mb-4`}>
          <IconServer />
          <div>
            <b>{data.source === 'LDAP' ? 'Conectado al servidor LDAP' : 'Directorio de respaldo (LDAP no disponible)'}</b>
            <div className="small" style={{ opacity: .9 }}>{data.message}</div>
          </div>
        </div>
      )}

      <div className="row between mb-3 wrap gap-3">
        <div className="row gap-2 muted small"><IconLdap width={16} height={16} /> {people.length} usuarios en el directorio</div>
        <SearchBox value={q} onChange={setQ} placeholder="Buscar en el directorio…" />
      </div>

      {loading ? <TableSkeleton rows={6} cols={5} /> : error ? <ErrorState message={error} onRetry={load} /> : people.length === 0 ? (
        <div className="card"><Empty icon={<IconLdap />} title="Sin resultados" hint="No se encontraron usuarios en el directorio." /></div>
      ) : (
        <div className="card table-wrap">
          <table className="data">
            <thead><tr><th>Usuario</th><th>Cargo</th><th>Departamento</th><th>Distinguished Name (DN)</th><th>Estado</th><th></th></tr></thead>
            <tbody>
              {people.map((p) => (
                <tr key={p.dn}>
                  <td><div className="row gap-3"><Avatar first={p.firstName} last={p.lastName} ldap /><div><div className="cell-strong">{p.firstName} {p.lastName}</div><div className="tiny dim mono">{p.username} · {p.email}</div></div></div></td>
                  <td className="small">{p.cargo || '—'}</td>
                  <td className="small">{p.department || '—'}</td>
                  <td className="tiny dim mono">{p.dn}</td>
                  <td>{p.imported ? <span className="badge badge-green"><IconCheck width={11} height={11} /> Integrado</span> : <span className="badge badge-gray">No integrado</span>}</td>
                  <td className="center">
                    {p.imported ? <span className="tiny dim">—</span>
                      : <button className="btn btn-gold btn-sm" onClick={() => setImporting(p)}><IconDownload width={14} height={14} /> Integrar</button>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {importing && <ImportModal person={importing} roles={roles} onClose={() => setImporting(null)} onDone={() => { setImporting(null); emitDataChanged(); load(); }} />}
    </>
  );
}

function ImportModal({ person, roles, onClose, onDone }: { person: LdapPerson; roles: Role[]; onClose: () => void; onDone: () => void }) {
  const toast = useToast();
  const [sel, setSel] = useState<string[]>([]);
  const doImport = async () => {
    try {
      await api.importLdap(person.username, sel);
      toast.success('Cliente final integrado', `${person.firstName} ${person.lastName} fue integrado desde LDAP.`);
      onDone();
    } catch (e) { toast.error('Error', (e as Error).message); }
  };
  return (
    <Modal title="Integrar cliente final desde LDAP" subtitle={`${person.firstName} ${person.lastName} · ${person.dn}`} onClose={onClose}
      footer={<><button className="btn btn-ghost" onClick={onClose}>Cancelar</button><button className="btn btn-gold" onClick={doImport}><IconDownload width={15} height={15} /> Integrar usuario</button></>}>
      <div className="card pad mb-4" style={{ background: 'var(--surface-2)' }}>
        <div className="row gap-3"><Avatar first={person.firstName} last={person.lastName} ldap size="lg" />
          <div><b>{person.firstName} {person.lastName}</b><div className="small muted">{person.cargo} · {person.department}</div><div className="tiny dim mono">{person.email}</div></div>
        </div>
      </div>
      <Field label="Asignar roles (opcional)">
        <div className="grid" style={{ gap: 8 }}>
          {roles.map((r) => {
            const checked = sel.includes(r.id);
            return (
              <label key={r.id} className={`check-card ${checked ? 'checked' : ''}`}>
                <input type="checkbox" checked={checked} onChange={() => setSel(checked ? sel.filter((x) => x !== r.id) : [...sel, r.id])} />
                <span className="icon-tile" style={{ width: 28, height: 28, background: r.color, fontSize: 11 }}>{r.name.slice(0, 2)}</span>
                <div className="grow"><div className="cc-title">{r.name}</div></div>
              </label>
            );
          })}
        </div>
      </Field>
    </Modal>
  );
}

// front-angular/src/app/pages/directory/directory.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';

import { TableModule } from 'primeng/table';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { EventsService } from '../../core/services/events.service';
import {
  TableSkeletonComponent,
  EmptyStateComponent,
  SearchBoxComponent,
  AvatarComponent,
} from '../../shared/components/ui';
import {
  IconLdapComponent,
  IconDownloadComponent,
  IconCheckComponent,
  IconUserPlusComponent,
} from '../../shared/components/icons';
import type { LdapPerson, Role } from '../../shared/models/types';

@Component({
  selector: 'app-directory',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    DialogModule,
    ButtonModule,
        TableModule,
    TableSkeletonComponent,
    EmptyStateComponent,
    SearchBoxComponent,
    AvatarComponent,
    IconLdapComponent,
    IconDownloadComponent,
    IconCheckComponent,
    IconUserPlusComponent,
  ],
  template: `
    <div class="page-head">
      <div>
        <h1>Directorio LDAP</h1>
        <p>Usuarios cliente final integrados desde el directorio corporativo. Importe un usuario para asignarle roles.</p>
      </div>
      <button class="btn btn-primary" (click)="loadLdapUsers()">
        <app-icon-download /> Sincronizar directorio
      </button>
    </div>

    <div class="card mb-4">
      <div class="card-body row gap-3">
        <app-icon-ldap [width]="32" [height]="32" style="color: var(--amber-600);" />
        <div>
          <b>Origen del directorio</b>
          <div class="small muted">
            Los usuarios cliente final se integran exclusivamente desde el directorio corporativo LDAP de Favorita Fruit Company.
          </div>
        </div>
        <div class="grow"></div>
        @if (ldapResponse()) {
          <span class="badge" [class.badge-green]="ldapResponse()!.source === 'LDAP'" [class.badge-amber]="ldapResponse()!.source === 'FALLBACK'">
            {{ ldapResponse()!.source === 'LDAP' ? 'LDAP conectado' : 'Modo offline' }}
          </span>
        }
      </div>
    </div>

    @if (loading()) {
      <app-table-skeleton [rows]="6" [cols]="5" />
    } @else if (ldapError()) {
      <div class="card">
        <div class="empty">
          <div class="empty-icon"><app-icon-ldap /></div>
          <h4>No se pudo conectar al directorio</h4>
          <p class="muted small">{{ ldapError() }}</p>
          <div class="mt-4">
            <button class="btn btn-primary" (click)="loadLdapUsers()">
              <app-icon-download /> Reintentar
            </button>
          </div>
        </div>
      </div>
    } @else if (ldapResponse()?.people?.length === 0) {
      <div class="card">
        <div class="empty">
          <div class="empty-icon"><app-icon-ldap /></div>
          <h4>Sin usuarios en el directorio</h4>
          <p class="muted small">No se encontraron usuarios en el directorio LDAP.</p>
        </div>
      </div>
    } @else {
      <div class="card table-wrap">
        <table class="data">
          <thead>
            <tr>
              <th>Usuario</th>
              <th>Email</th>
              <th>Cargo</th>
              <th>Departamento</th>
              <th>DN</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @for (p of filteredLdapUsers(); track p.username) {
              <tr>
                <td>
                  <div class="row gap-3">
                    <app-avatar [first]="p.firstName" [last]="p.lastName" [ldap]="true" />
                    <div>
                      <div class="cell-strong">{{ p.firstName }} {{ p.lastName }}</div>
                      <div class="tiny dim mono">{{ p.username }}</div>
                    </div>
                  </div>
                </td>
                <td>{{ p.email }}</td>
                <td>{{ p.cargo || '—' }}</td>
                <td>{{ p.department || '—' }}</td>
                <td class="mono tiny dim">{{ p.dn }}</td>
                <td>
                  @if (p.imported) {
                    <span class="badge badge-green">
                      <app-icon-check [width]="12" [height]="12" /> Importado
                    </span>
                  } @else {
                    <button class="btn btn-primary btn-sm" (click)="openImport(p)">
                      <app-icon-user-plus [width]="14" [height]="14" /> Importar
                    </button>
                  }
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }

    <p-dialog
      [(visible)]="showImportDialog"
      header="Importar usuario desde LDAP"
      [modal]="true"
      [style]="{ width: '560px' }"
      [closable]="true"
      (onHide)="closeImportDialog()"
    >
      @if (ldapPerson) {
        <div class="card pad mb-4" style="background: var(--surface-2);">
          <div class="row gap-3">
            <app-avatar [first]="ldapPerson.firstName" [last]="ldapPerson.lastName" [ldap]="true" size="lg" />
            <div>
              <b style="font-size: 16px;">{{ ldapPerson.firstName }} {{ ldapPerson.lastName }}</b>
              <div class="mono tiny dim">{{ ldapPerson.username }}</div>
              <div class="small muted">{{ ldapPerson.email }}</div>
            </div>
          </div>
        </div>

        <div class="field">
          <label>Asignar roles (opcional)</label>
          <div class="grid" style="gap: 8px; margin-top: 8px;">
            @for (r of roles(); track r.id) {
              <label class="check-card" [class.checked]="isRoleSelected(r.id)">
                <input
                  type="checkbox"
                  [checked]="isRoleSelected(r.id)"
                  (change)="toggleRole(r.id)"
                />
                <div class="grow">
                  <div class="cc-title">{{ r.name }}</div>
                  <div class="cc-desc">{{ r.description }}</div>
                </div>
              </label>
            }
          </div>
        </div>
      }
      <ng-template pTemplate="footer">
        <button class="btn btn-ghost" (click)="closeImportDialog()">Cancelar</button>
        <button class="btn btn-primary" (click)="importUser()">
          <app-icon-download /> Importar Usuario
        </button>
      </ng-template>
    </p-dialog>
  `,
})
export class DirectoryComponent implements OnInit {
  private api = inject(ApiService);
  private toast = inject(ToastService);
  private events = inject(EventsService);

  ldapResponse = signal<{ source: 'LDAP' | 'FALLBACK'; message: string; people: LdapPerson[] } | null>(null);
  ldapError = signal<string | null>(null);
  roles = signal<Role[]>([]);
  loading = signal(false);
  q = signal('');

  showImportDialog = false;
  ldapPerson: LdapPerson | null = null;
  selectedRoleIds: string[] = [];

  ngOnInit(): void {
    this.loadLdapUsers();
    this.loadRoles();
  }

  loadRoles(): void {
    this.api.listRoles().subscribe({
      next: (r) => this.roles.set(r),
      error: () => {},
    });
  }

  loadLdapUsers(): void {
    this.loading.set(true);
    this.ldapError.set(null);
    this.api.ldapUsers().subscribe({
      next: (res) => {
        this.ldapResponse.set(res);
        this.loading.set(false);
      },
      error: (e) => {
        this.ldapError.set(e.message);
        this.loading.set(false);
      },
    });
  }

  filteredLdapUsers(): LdapPerson[] {
    const query = this.q().toLowerCase();
    if (!query) return this.ldapResponse()?.people || [];
    return (this.ldapResponse()?.people || []).filter(
      (p) => `${p.firstName} ${p.lastName} ${p.username} ${p.email} ${p.department}`.toLowerCase().includes(query)
    );
  }

  openImport(p: LdapPerson): void {
    this.ldapPerson = p;
    this.selectedRoleIds = [];
    this.showImportDialog = true;
  }

  closeImportDialog(): void {
    this.showImportDialog = false;
    this.ldapPerson = null;
  }

  isRoleSelected(roleId: string): boolean {
    return this.selectedRoleIds.includes(roleId);
  }

  toggleRole(roleId: string): void {
    const idx = this.selectedRoleIds.indexOf(roleId);
    if (idx >= 0) {
      this.selectedRoleIds = this.selectedRoleIds.filter((id) => id !== roleId);
    } else {
      this.selectedRoleIds = [...this.selectedRoleIds, roleId];
    }
  }

  importUser(): void {
    if (!this.ldapPerson) return;
    this.api.importLdap(this.ldapPerson.username, this.selectedRoleIds).subscribe({
      next: () => {
        this.toast.success('Usuario importado', `${this.ldapPerson!.firstName} ${this.ldapPerson!.lastName} fue agregado a la consola.`);
        this.events.emitDataChanged();
        this.closeImportDialog();
        this.loadLdapUsers();
      },
      error: (e) => {
        this.toast.error('Error al importar', e.message);
      },
    });
  }
}
