// front-angular/src/app/pages/users/users.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';

import { TableModule } from 'primeng/table';
import { ConfirmDialogModule } from 'primeng/confirmdialog';

import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { EventsService } from '../../core/services/events.service';
import {
  TableSkeletonComponent,
  ErrorStateComponent,
  EmptyStateComponent,
  SearchBoxComponent,
  AvatarComponent,
  TypeBadgeComponent,
  SourceBadgeComponent,
} from '../../shared/components/ui';
import {
  IconPlusComponent,
  IconUsersComponent,
  IconTrashComponent,
  IconEditComponent,
  IconRolesComponent,
  IconShieldComponent,
  IconLdapComponent,
  IconUserPlusComponent,
  IconDownloadComponent,
  IconCheckComponent,
  IconCloseComponent,
} from '../../shared/components/icons';
import type { LdapPerson, Role, User, UserType } from '../../shared/models/types';

type Tab = 'ALL' | 'ADMIN' | 'CLIENTE_FINAL';

interface UserForm {
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  cargo: string;
  department: string;
  password: string;
  source: 'LOCAL' | 'LDAP';
  roleIds: string[];
}

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    DialogModule,
    ButtonModule,
    InputTextModule,
    TableModule,
    ConfirmDialogModule,
    TableSkeletonComponent,
    ErrorStateComponent,
    EmptyStateComponent,
    SearchBoxComponent,
    AvatarComponent,
    TypeBadgeComponent,
    SourceBadgeComponent,
    IconPlusComponent,
    IconUsersComponent,
    IconTrashComponent,
    IconEditComponent,
    IconRolesComponent,
    IconShieldComponent,
    IconLdapComponent,
    IconUserPlusComponent,
    IconDownloadComponent,
    IconCheckComponent,
    IconCloseComponent,
  ],
  template: `
    <div class="page-head">
      <div>
        <h1>Usuarios</h1>
        <p>Los administradores se crean localmente en la consola; los clientes finales se integran exclusivamente desde LDAP. A todos se les asignan roles.</p>
      </div>
    </div>

    <div class="tabs mb-4">
      <button [class.active]="tab() === 'ALL'" (click)="tab.set('ALL')">
        Todos ({{ totalCount }})
      </button>
      <button [class.active]="tab() === 'ADMIN'" (click)="tab.set('ADMIN')">
        Administradores ({{ adminCount }})
      </button>
      <button [class.active]="tab() === 'CLIENTE_FINAL'" (click)="tab.set('CLIENTE_FINAL')">
        Clientes finales ({{ clienteFinalCount }})
      </button>
    </div>

    <div class="row between mb-4">
      <app-search-box [value]="q()" (valueChange)="q.set($event)" placeholder="Buscar usuario…" />
      <button class="btn btn-primary" (click)="showCreateDialog = true">
        <app-icon-user-plus /> Nuevo Usuario
      </button>
    </div>

    @if (loading()) {
      <app-table-skeleton [rows]="6" [cols]="6" />
    } @else if (error()) {
      <app-error-state [message]="error()!" [onRetry]="load" />
    } @else if (filtered().length === 0) {
      <div class="card">
        <div class="empty">
          <div class="empty-icon"><app-icon-users /></div>
          <h4>Sin usuarios</h4>
          <p class="muted small">Cree un administrador local o integre un cliente final desde LDAP.</p>
          <div class="mt-4">
            <button class="btn btn-primary" (click)="showCreateDialog = true">
              <app-icon-user-plus /> Nuevo Usuario
            </button>
          </div>
        </div>
      </div>
    } @else {
      <div class="card table-wrap">
        <table class="data">
          <thead>
            <tr>
              <th>Usuario</th>
              <th>Cargo / Departamento</th>
              <th>Tipo</th>
              <th>Origen</th>
              <th>Roles</th>
              <th>Estado</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @for (u of filtered(); track u.id) {
              <tr>
                <td>
                  <div class="row gap-3">
                    <app-avatar [first]="u.firstName" [last]="u.lastName" [ldap]="u.source === 'LDAP'" />
                    <div>
                      <div class="cell-strong">{{ u.firstName }} {{ u.lastName }}</div>
                      <div class="tiny dim mono">{{ u.username }}</div>
                    </div>
                  </div>
                </td>
                <td>
                  <div>{{ u.cargo || '—' }}</div>
                  <div class="tiny dim">{{ u.department || '—' }}</div>
                </td>
                <td><app-type-badge [type]="u.type" /></td>
                <td><app-source-badge [source]="u.source" /></td>
                <td>
                  @if (u.roleIds.length === 0) {
                    <span class="muted small">Sin roles</span>
                  } @else {
                    <div class="row gap-2 wrap">
                      @for (rid of u.roleIds.slice(0, 2); track rid) {
                        <span class="badge badge-gray">{{ getRoleName(rid) }}</span>
                      }
                      @if (u.roleIds.length > 2) {
                        <span class="badge badge-gray">+{{ u.roleIds.length - 2 }}</span>
                      }
                    </div>
                  }
                </td>
                <td>
                  <span class="badge" [class.badge-green]="u.status === 'ACTIVE'" [class.badge-gray]="u.status !== 'ACTIVE'">
                    {{ u.status === 'ACTIVE' ? 'Activo' : 'Inactivo' }}
                  </span>
                </td>
                <td>
                  <div class="cell-actions">
                    <button class="btn btn-ghost btn-sm btn-icon" title="Editar" (click)="openEdit(u)">
                      <app-icon-edit [width]="15" [height]="15" />
                    </button>
                    <button class="btn btn-ghost btn-sm btn-icon" title="Asignar roles" (click)="openRoles(u)">
                      <app-icon-roles [width]="15" [height]="15" />
                    </button>
                    @if (u.source === 'LOCAL') {
                      <button class="btn btn-danger btn-sm btn-icon" title="Eliminar" (click)="confirmDelete(u)">
                        <app-icon-trash [width]="15" [height]="15" />
                      </button>
                    }
                  </div>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }

    <p-dialog
      [(visible)]="showCreateDialog"
      header="Nuevo usuario"
      [modal]="true"
      [style]="{ width: '560px' }"
      [closable]="true"
      (onHide)="closeCreateDialog()"
    >
      <div class="field">
        <label>Origen</label>
        <select class="select" [(ngModel)]="userForm.source">
          <option value="LOCAL">Local</option>
          <option value="LDAP">LDAP</option>
        </select>
      </div>
      <div class="form-grid">
        <div class="field">
          <label>Usuario</label>
          <input class="input" [(ngModel)]="userForm.username" placeholder="juan.perez" />
        </div>
        <div class="field">
          <label>Contraseña</label>
          <input class="input" type="password" [(ngModel)]="userForm.password" placeholder="••••••••" />
        </div>
      </div>
      <div class="form-grid">
        <div class="field">
          <label>Nombre</label>
          <input class="input" [(ngModel)]="userForm.firstName" placeholder="Juan" />
        </div>
        <div class="field">
          <label>Apellido</label>
          <input class="input" [(ngModel)]="userForm.lastName" placeholder="Pérez" />
        </div>
      </div>
      <div class="form-grid">
        <div class="field">
          <label>Email</label>
          <input class="input" type="email" [(ngModel)]="userForm.email" placeholder="juan.perez@reybanpac.com" />
        </div>
        <div class="field">
          <label>Cargo</label>
          <input class="input" [(ngModel)]="userForm.cargo" placeholder="Analista de Sistemas" />
        </div>
      </div>
      <div class="field">
        <label>Departamento</label>
        <input class="input" [(ngModel)]="userForm.department" placeholder="Tecnología" />
      </div>
      <ng-template pTemplate="footer">
        <button class="btn btn-ghost" (click)="closeCreateDialog()">Cancelar</button>
        <button class="btn btn-primary" (click)="createUser()">Crear Usuario</button>
      </ng-template>
    </p-dialog>

    <p-dialog
      [(visible)]="showEditDialog"
      header="Editar usuario"
      [modal]="true"
      [style]="{ width: '560px' }"
      [closable]="true"
      (onHide)="closeEditDialog()"
    >
      @if (editUser) {
        <div class="field">
          <label>Origen</label>
          <select class="select" [(ngModel)]="userForm.source">
            <option value="LOCAL">Local</option>
            <option value="LDAP">LDAP</option>
          </select>
        </div>
        <div class="form-grid">
          <div class="field">
            <label>Usuario</label>
            <input class="input" [(ngModel)]="userForm.username" />
          </div>
          <div class="field">
            <label>Nueva contraseña</label>
            <input class="input" type="password" [(ngModel)]="userForm.password" placeholder="Dejar en blanco para no cambiar" />
          </div>
        </div>
        <div class="form-grid">
          <div class="field">
            <label>Nombre</label>
            <input class="input" [(ngModel)]="userForm.firstName" />
          </div>
          <div class="field">
            <label>Apellido</label>
            <input class="input" [(ngModel)]="userForm.lastName" />
          </div>
        </div>
        <div class="form-grid">
          <div class="field">
            <label>Email</label>
            <input class="input" type="email" [(ngModel)]="userForm.email" />
          </div>
          <div class="field">
            <label>Cargo</label>
            <input class="input" [(ngModel)]="userForm.cargo" />
          </div>
        </div>
        <div class="field">
          <label>Departamento</label>
          <input class="input" [(ngModel)]="userForm.department" />
        </div>
      }
      <ng-template pTemplate="footer">
        <button class="btn btn-ghost" (click)="closeEditDialog()">Cancelar</button>
        <button class="btn btn-primary" (click)="updateUser()">Guardar Cambios</button>
      </ng-template>
    </p-dialog>

    <p-dialog
      [(visible)]="showRolesDialog"
      header="Asignar roles"
      [modal]="true"
      [style]="{ width: '560px' }"
      [closable]="true"
      (onHide)="closeRolesDialog()"
    >
      @if (rolesUser) {
        <div class="mb-4 row gap-3">
          <app-avatar [first]="rolesUser.firstName" [last]="rolesUser.lastName" [ldap]="rolesUser.source === 'LDAP'" />
          <div>
            <b>{{ rolesUser.firstName }} {{ rolesUser.lastName }}</b>
            <div class="tiny dim mono">{{ rolesUser.username }}</div>
          </div>
        </div>
        <div class="field">
          <label>Seleccionar roles</label>
          <div class="grid" style="gap: 8px; margin-top: 8px;">
            @for (r of roles(); track r.id) {
              <label class="check-card" [class.checked]="isRoleSelected(r.id)">
                <input
                  type="checkbox"
                  [checked]="isRoleSelected(r.id)"
                  (change)="toggleRole(r.id)"
                />
                <div class="grow">
                  <div class="row gap-2">
                    <span class="cc-title">{{ r.name }}</span>
                    @if (r.isAdmin) {
                      <app-icon-shield [width]="12" [height]="12" />
                    }
                  </div>
                  <div class="cc-desc">{{ r.description }}</div>
                </div>
              </label>
            }
          </div>
        </div>
      }
      <ng-template pTemplate="footer">
        <button class="btn btn-ghost" (click)="closeRolesDialog()">Cancelar</button>
        <button class="btn btn-primary" (click)="saveRoles()">Guardar Roles</button>
      </ng-template>
    </p-dialog>

    <p-confirmDialog></p-confirmDialog>
  `,
})
export class UsersComponent implements OnInit {
  private api = inject(ApiService);
  private toast = inject(ToastService);
  private events = inject(EventsService);

  users = signal<User[]>([]);
  roles = signal<Role[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);
  tab = signal<Tab>('ALL');
  q = signal('');

  showCreateDialog = false;
  showEditDialog = false;
  showRolesDialog = false;
  editUser: User | null = null;
  rolesUser: User | null = null;
  userForm: UserForm = this.blankForm();
  selectedRoleIds: string[] = [];

  load = () => this.loadData();

  get totalCount(): number { return this.users().length; }
  get adminCount(): number { return this.users().filter(u => u.type === 'ADMIN').length; }
  get clienteFinalCount(): number { return this.users().filter(u => u.type === 'CLIENTE_FINAL').length; }

  ngOnInit(): void {
    this.loadData();
    this.events.onDataChanged(() => this.loadData());
  }

  loadData(): void {
    this.loading.set(true);
    this.error.set(null);
    Promise.all([
      this.api.listUsers().toPromise(),
      this.api.listRoles().toPromise(),
    ]).then(([u, r]) => {
      this.users.set(u || []);
      this.roles.set(r || []);
    }).catch((e) => {
      this.error.set(e.message);
    }).finally(() => {
      this.loading.set(false);
    });
  }

  blankForm(): UserForm {
    return { username: '', firstName: '', lastName: '', email: '', cargo: '', department: '', password: '', source: 'LOCAL', roleIds: [] };
  }

  filtered(): User[] {
    return this.users()
      .filter(u => this.tab() === 'ALL' || u.type === this.tab())
      .filter(u => `${u.firstName} ${u.lastName} ${u.username} ${u.cargo} ${u.department}`.toLowerCase().includes(this.q().toLowerCase()));
  }

  getRoleName(roleId: string): string {
    const role = this.roles().find(r => r.id === roleId);
    return role?.name || roleId;
  }

  closeCreateDialog(): void {
    this.showCreateDialog = false;
    this.userForm = this.blankForm();
  }

  openEdit(u: User): void {
    this.editUser = u;
    this.userForm = {
      username: u.username,
      firstName: u.firstName,
      lastName: u.lastName,
      email: u.email,
      cargo: u.cargo,
      department: u.department,
      password: '',
      source: u.source,
      roleIds: [...u.roleIds],
    };
    this.showEditDialog = true;
  }

  closeEditDialog(): void {
    this.showEditDialog = false;
    this.editUser = null;
  }

  openRoles(u: User): void {
    this.rolesUser = u;
    this.selectedRoleIds = [...u.roleIds];
    this.showRolesDialog = true;
  }

  closeRolesDialog(): void {
    this.showRolesDialog = false;
    this.rolesUser = null;
  }

  isRoleSelected(roleId: string): boolean {
    return this.selectedRoleIds.includes(roleId);
  }

  toggleRole(roleId: string): void {
    const idx = this.selectedRoleIds.indexOf(roleId);
    if (idx >= 0) {
      this.selectedRoleIds = this.selectedRoleIds.filter(id => id !== roleId);
    } else {
      this.selectedRoleIds = [...this.selectedRoleIds, roleId];
    }
  }

  async createUser(): Promise<void> {
    if (!this.userForm.username || !this.userForm.password || !this.userForm.firstName) {
      this.toast.error('Faltan datos', 'Usuario, contraseña y nombre son obligatorios.');
      return;
    }
    try {
      await this.api.createUser(this.userForm).toPromise();
      this.toast.success('Usuario creado', `${this.userForm.firstName} ${this.userForm.lastName} fue agregado.`);
      this.events.emitDataChanged();
      this.closeCreateDialog();
      this.loadData();
    } catch (e: any) {
      this.toast.error('Error', e.message);
    }
  }

  async updateUser(): Promise<void> {
    if (!this.editUser) return;
    if (!this.userForm.username || !this.userForm.firstName) {
      this.toast.error('Faltan datos');
      return;
    }
    const payload: any = {
      username: this.userForm.username,
      firstName: this.userForm.firstName,
      lastName: this.userForm.lastName,
      email: this.userForm.email,
      cargo: this.userForm.cargo,
      department: this.userForm.department,
      source: this.userForm.source,
    };
    if (this.userForm.password) {
      payload.password = this.userForm.password;
    }
    try {
      await this.api.updateUser(this.editUser.id, payload).toPromise();
      this.toast.success('Usuario actualizado');
      this.events.emitDataChanged();
      this.closeEditDialog();
      this.loadData();
    } catch (e: any) {
      this.toast.error('Error', e.message);
    }
  }

  async saveRoles(): Promise<void> {
    if (!this.rolesUser) return;
    try {
      await this.api.setUserRoles(this.rolesUser.id, this.selectedRoleIds).toPromise();
      this.toast.success('Roles actualizados');
      this.events.emitDataChanged();
      this.closeRolesDialog();
      this.loadData();
    } catch (e: any) {
      this.toast.error('Error', e.message);
    }
  }

  confirmDelete(u: User): void {
    if (confirm(`¿Eliminar a ${u.firstName} ${u.lastName}?`)) {
      this.remove(u);
    }
  }

  async remove(u: User): Promise<void> {
    try {
      await this.api.deleteUser(u.id).toPromise();
      this.toast.success('Usuario eliminado');
      this.events.emitDataChanged();
      this.loadData();
    } catch (e: any) {
      this.toast.error('Error', e.message);
    }
  }
}

// frontend/src/pages/Users.tsx
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import type { LdapPerson, Role, User } from '../types';
import { useToast } from '../context/ToastContext';
import { emitDataChanged } from '../lib/events';
import {
  Modal, Field, Empty, Confirm, Avatar, TypeBadge, SourceBadge, SearchBox, TableSkeleton, ErrorState,
} from '../components/ui';
import {
  IconPlus, IconUsers, IconTrash, IconEdit, IconRoles, IconShield, IconLdap,
  IconUserPlus, IconDownload, IconCheck,
} from '../components/icons';

type Tab = 'ALL' | 'ADMIN' | 'CLIENTE_FINAL';
const localBlank = { username: '', firstName: '', lastName: '', email: '', cargo: '', department: '', password: '', roleIds: [] as string[] };

export default function Users() {
  const toast = useToast();
  const [users, setUsers] = useState<User[]>([]);
  const [roles, setRoles] = useState<Role[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>('ALL');
  const [q, setQ] = useState('');

  const [creating, setCreating] = useState(false);
  const [editUser, setEditUser] = useState<User | null>(null);
  const [rolesUser, setRolesUser] = useState<User | null>(null);
  const [toDelete, setToDelete] = useState<User | null>(null);

  const load = async () => {
    setLoading(true); setError(null);
    try {
      const [u, r] = await Promise.all([api.listUsers(), api.listRoles()]);
      setUsers(u); setRoles(r);
    } catch (e) { setError((e as Error).message); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const roleById = (id: string) => roles.find((r) => r.id === id);
  const filtered = users
    .filter((u) => tab === 'ALL' || u.type === tab)
    .filter((u) => `${u.firstName} ${u.lastName} ${u.username} ${u.cargo} ${u.department}`.toLowerCase().includes(q.toLowerCase()));

  const remove = async (u: User) => {
    try { await api.deleteUser(u.id); toast.success('Usuario eliminado'); emitDataChanged(); load(); }
    catch (e) { toast.error('Error', (e as Error).message); }
  };

  return (
    <>
      <div className="page-head">
        <div>
          <h1>Usuarios</h1>
          <p>Los administradores se crean localmente en la consola; los clientes finales se integran exclusivamente desde LDAP. A todos se les asignan roles.</p>
        </div>
        <button className="btn btn-primary" onClick={() => setCreating(true)}><IconUserPlus /> Nuevo Usuario</button>
      </div>

      <div className="row between mb-4 wrap gap-3">
        <div className="tabs" role="tablist" aria-label="Filtrar usuarios por tipo">
          <button role="tab" aria-selected={tab === 'ALL'} className={tab === 'ALL' ? 'active' : ''} onClick={() => setTab('ALL')}>Todos ({users.length})</button>
          <button role="tab" aria-selected={tab === 'ADMIN'} className={tab === 'ADMIN' ? 'active' : ''} onClick={() => setTab('ADMIN')}>Administradores ({users.filter((u) => u.type === 'ADMIN').length})</button>
          <button role="tab" aria-selected={tab === 'CLIENTE_FINAL'} className={tab === 'CLIENTE_FINAL' ? 'active' : ''} onClick={() => setTab('CLIENTE_FINAL')}>Clientes finales ({users.filter((u) => u.type === 'CLIENTE_FINAL').length})</button>
        </div>
        <SearchBox value={q} onChange={setQ} placeholder="Buscar usuario…" />
      </div>

      {loading ? <TableSkeleton rows={6} cols={6} /> : error ? <ErrorState message={error} onRetry={load} /> : filtered.length === 0 ? (
        <div className="card"><Empty icon={<IconUsers />} title="Sin usuarios" hint="Cree un administrador local o integre un cliente final desde LDAP."
          action={<button className="btn btn-primary" onClick={() => setCreating(true)}><IconUserPlus /> Nuevo Usuario</button>} /></div>
      ) : (
        <div className="card table-wrap">
          <table className="data">
            <thead><tr><th>Usuario</th><th>Cargo / Departamento</th><th>Tipo</th><th>Origen</th><th>Roles</th><th>Estado</th><th></th></tr></thead>
            <tbody>
              {filtered.map((u) => (
                <tr key={u.id}>
                  <td>
                    <div className="row gap-3">
                      <Avatar first={u.firstName} last={u.lastName} ldap={u.source === 'LDAP'} />
                      <div>
                        <div className="cell-strong">{u.firstName} {u.lastName}</div>
                        <div className="tiny dim mono">{u.username} · {u.email}</div>
                      </div>
                    </div>
                  </td>
                  <td><div className="small">{u.cargo || '—'}</div><div className="tiny dim">{u.department || '—'}</div></td>
                  <td><TypeBadge type={u.type} /></td>
                  <td><SourceBadge source={u.source} /></td>
                  <td>
                    {u.roleIds.length === 0 ? <span className="tiny dim">Sin roles</span> : (
                      <div className="row gap-2 wrap">
                        {u.roleIds.slice(0, 2).map((id) => { const r = roleById(id); return r ? <span key={id} className="badge badge-blue" style={{ background: r.color + '18', color: r.color, borderColor: r.color + '30' }}>{r.name}</span> : null; })}
                        {u.roleIds.length > 2 && <span className="badge badge-gray">+{u.roleIds.length - 2}</span>}
                      </div>
                    )}
                  </td>
                  <td>{u.status === 'ACTIVE' ? <span className="badge badge-green"><span className="dot" />Activo</span> : <span className="badge badge-gray">Inactivo</span>}</td>
                  <td>
                    <div className="cell-actions">
                      <button className="btn btn-ghost btn-sm btn-icon" title="Asignar roles" aria-label={`Asignar roles a ${u.firstName} ${u.lastName}`} onClick={() => setRolesUser(u)}><IconRoles width={15} height={15} /></button>
                      <button className="btn btn-ghost btn-sm btn-icon" title="Editar" aria-label={`Editar a ${u.firstName} ${u.lastName}`} onClick={() => setEditUser(u)}><IconEdit width={15} height={15} /></button>
                      <button className="btn btn-danger btn-sm btn-icon" title="Eliminar" aria-label={`Eliminar a ${u.firstName} ${u.lastName}`} onClick={() => setToDelete(u)}><IconTrash width={15} height={15} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {creating && <CreateUserModal roles={roles} existing={users} onClose={() => setCreating(false)} onDone={() => { setCreating(false); emitDataChanged(); load(); }} />}
      {editUser && <EditUserModal user={editUser} onClose={() => setEditUser(null)} onDone={() => { setEditUser(null); load(); }} />}
      {rolesUser && <AssignRolesModal user={rolesUser} roles={roles} onClose={() => setRolesUser(null)} onDone={() => { setRolesUser(null); emitDataChanged(); load(); }} />}
      {toDelete && <Confirm title="Eliminar usuario" message={`¿Eliminar a ${toDelete.firstName} ${toDelete.lastName}?`} onConfirm={() => remove(toDelete)} onClose={() => setToDelete(null)} />}
    </>
  );
}

/* ------------------------- Crear usuario ------------------------- */
function CreateUserModal({ roles, existing, onClose, onDone }: { roles: Role[]; existing: User[]; onClose: () => void; onDone: () => void }) {
  const toast = useToast();
  const [mode, setMode] = useState<'ADMIN' | 'CLIENTE_FINAL'>('ADMIN');
  const [local, setLocal] = useState({ ...localBlank });
  const [ldap, setLdap] = useState<LdapPerson[]>([]);
  const [ldapSource, setLdapSource] = useState<string>('');
  const [ldapMsg, setLdapMsg] = useState<string>('');
  const [loadingLdap, setLoadingLdap] = useState(false);
  const [importingRoles, setImportingRoles] = useState<string[]>([]);

  useEffect(() => {
    if (mode === 'CLIENTE_FINAL' && ldap.length === 0) {
      setLoadingLdap(true);
      api.ldapUsers().then((r) => { setLdap(r.people); setLdapSource(r.source); setLdapMsg(r.message); }).finally(() => setLoadingLdap(false));
    }
  }, [mode]);

  const createLocal = async () => {
    if (!local.username || !local.firstName) return toast.error('Faltan datos', 'Usuario y nombre son obligatorios.');
    try {
      await api.createUser({ ...local, type: 'ADMIN', source: 'LOCAL', password: local.password || 'changeme' });
      toast.success('Administrador creado', `${local.firstName} fue creado localmente.`);
      onDone();
    } catch (e) { toast.error('Error', (e as Error).message); }
  };

  const importLdap = async (p: LdapPerson) => {
    try {
      await api.importLdap(p.username, importingRoles);
      toast.success('Cliente final integrado', `${p.firstName} ${p.lastName} se importó desde LDAP.`);
      onDone();
    } catch (e) { toast.error('Error', (e as Error).message); }
  };

  return (
    <Modal wide title="Nuevo usuario" subtitle="Elija el tipo de usuario que desea crear." onClose={onClose}
      footer={mode === 'ADMIN' ? <>
        <button className="btn btn-ghost" onClick={onClose}>Cancelar</button>
        <button className="btn btn-primary" onClick={createLocal}>Crear Administrador</button>
      </> : <button className="btn btn-ghost" onClick={onClose}>Cerrar</button>}>

      <div className="grid cols-2 mb-4">
        <button className={`check-card ${mode === 'ADMIN' ? 'checked' : ''}`} onClick={() => setMode('ADMIN')} style={{ textAlign: 'left' }}>
          <span className="icon-tile" style={{ width: 36, height: 36, background: 'var(--navy-600)' }}><IconShield width={18} height={18} /></span>
          <div><div className="cc-title">Administrador</div><div className="cc-desc">Se crea localmente en la consola, con contraseña.</div></div>
        </button>
        <button className={`check-card ${mode === 'CLIENTE_FINAL' ? 'checked' : ''}`} onClick={() => setMode('CLIENTE_FINAL')} style={{ textAlign: 'left' }}>
          <span className="icon-tile ldap" style={{ width: 36, height: 36, background: 'var(--amber-600)' }}><IconLdap width={18} height={18} /></span>
          <div><div className="cc-title">Cliente final</div><div className="cc-desc">Se integra exclusivamente desde el directorio LDAP.</div></div>
        </button>
      </div>

      {mode === 'ADMIN' ? (
        <>
          <div className="form-grid">
            <Field label="Usuario"><input className="input" value={local.username} onChange={(e) => setLocal({ ...local, username: e.target.value })} placeholder="jperez" /></Field>
            <Field label="Correo"><input className="input" value={local.email} onChange={(e) => setLocal({ ...local, email: e.target.value })} placeholder="jperez@reybanpac.com" /></Field>
            <Field label="Nombres"><input className="input" value={local.firstName} onChange={(e) => setLocal({ ...local, firstName: e.target.value })} /></Field>
            <Field label="Apellidos"><input className="input" value={local.lastName} onChange={(e) => setLocal({ ...local, lastName: e.target.value })} /></Field>
            <Field label="Cargo"><input className="input" value={local.cargo} onChange={(e) => setLocal({ ...local, cargo: e.target.value })} /></Field>
            <Field label="Departamento"><input className="input" value={local.department} onChange={(e) => setLocal({ ...local, department: e.target.value })} /></Field>
          </div>
          <Field label="Contraseña" hint="Credencial local para iniciar sesión. El administrador debería cambiarla en el primer ingreso."><input className="input" type="password" value={local.password} onChange={(e) => setLocal({ ...local, password: e.target.value })} placeholder="••••••••" /></Field>
          <Field label="Roles iniciales (opcional)">
            <div className="grid cols-2">
              {roles.map((r) => {
                const checked = local.roleIds.includes(r.id);
                return (
                  <label key={r.id} className={`check-card ${checked ? 'checked' : ''}`}>
                    <input type="checkbox" checked={checked} onChange={() => setLocal({ ...local, roleIds: checked ? local.roleIds.filter((x) => x !== r.id) : [...local.roleIds, r.id] })} />
                    <div><div className="cc-title">{r.name}</div></div>
                  </label>
                );
              })}
            </div>
          </Field>
        </>
      ) : (
        <>
          <div className={`banner ${ldapSource === 'LDAP' ? 'banner-ok' : 'banner-warn'} mb-4`}>
            <IconLdap /> {loadingLdap ? 'Consultando directorio LDAP…' : ldapMsg || 'Directorio LDAP'}
          </div>
          <Field label="Roles a asignar al importar (opcional)">
            <div className="row gap-2 wrap">
              {roles.map((r) => {
                const checked = importingRoles.includes(r.id);
                return <button key={r.id} className={`badge ${checked ? 'badge-blue' : 'badge-gray'}`} onClick={() => setImportingRoles(checked ? importingRoles.filter((x) => x !== r.id) : [...importingRoles, r.id])} style={{ cursor: 'pointer' }}>{checked && <IconCheck width={11} height={11} />}{r.name}</button>;
              })}
            </div>
          </Field>
          <div className="table-wrap card mt-3">
            <table className="data">
              <thead><tr><th>Usuario LDAP</th><th>Cargo</th><th>DN</th><th></th></tr></thead>
              <tbody>
                {ldap.map((p) => {
                  const already = existing.some((u) => u.username.toLowerCase() === p.username.toLowerCase()) || p.imported;
                  return (
                    <tr key={p.dn}>
                      <td><div className="row gap-3"><Avatar first={p.firstName} last={p.lastName} ldap size="sm" /><div><div className="cell-strong small">{p.firstName} {p.lastName}</div><div className="tiny dim mono">{p.username}</div></div></div></td>
                      <td className="small">{p.cargo || '—'}<div className="tiny dim">{p.department}</div></td>
                      <td className="tiny dim mono">{p.dn}</td>
                      <td className="center">
                        {already ? <span className="badge badge-green"><IconCheck width={11} height={11} /> Integrado</span>
                          : <button className="btn btn-gold btn-sm" onClick={() => importLdap(p)}><IconDownload width={14} height={14} /> Integrar</button>}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </>
      )}
    </Modal>
  );
}

/* ------------------------- Editar usuario ------------------------- */
function EditUserModal({ user, onClose, onDone }: { user: User; onClose: () => void; onDone: () => void }) {
  const toast = useToast();
  const [f, setF] = useState({ firstName: user.firstName, lastName: user.lastName, email: user.email, cargo: user.cargo, department: user.department, status: user.status, password: '' });
  const save = async () => {
    try { await api.updateUser(user.id, f); toast.success('Usuario actualizado'); onDone(); }
    catch (e) { toast.error('Error', (e as Error).message); }
  };
  return (
    <Modal title={`Editar · ${user.firstName} ${user.lastName}`} subtitle={user.source === 'LDAP' ? 'Usuario integrado desde LDAP' : 'Administrador local'} onClose={onClose}
      footer={<><button className="btn btn-ghost" onClick={onClose}>Cancelar</button><button className="btn btn-primary" onClick={save}>Guardar</button></>}>
      <div className="form-grid">
        <Field label="Nombres"><input className="input" value={f.firstName} onChange={(e) => setF({ ...f, firstName: e.target.value })} /></Field>
        <Field label="Apellidos"><input className="input" value={f.lastName} onChange={(e) => setF({ ...f, lastName: e.target.value })} /></Field>
        <Field label="Correo"><input className="input" value={f.email} onChange={(e) => setF({ ...f, email: e.target.value })} /></Field>
        <Field label="Estado">
          <select className="select" value={f.status} onChange={(e) => setF({ ...f, status: e.target.value as User['status'] })}><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select>
        </Field>
        <Field label="Cargo"><input className="input" value={f.cargo} onChange={(e) => setF({ ...f, cargo: e.target.value })} /></Field>
        <Field label="Departamento"><input className="input" value={f.department} onChange={(e) => setF({ ...f, department: e.target.value })} /></Field>
      </div>
      {user.source === 'LOCAL' && <Field label="Nueva contraseña" hint="Dejar vacío para no cambiarla."><input className="input" value={f.password} onChange={(e) => setF({ ...f, password: e.target.value })} placeholder="••••••" /></Field>}
    </Modal>
  );
}

/* ------------------------- Asignar roles ------------------------- */
function AssignRolesModal({ user, roles, onClose, onDone }: { user: User; roles: Role[]; onClose: () => void; onDone: () => void }) {
  const toast = useToast();
  const [sel, setSel] = useState<string[]>([...user.roleIds]);
  const save = async () => {
    try { await api.setUserRoles(user.id, sel); toast.success('Roles asignados', `${sel.length} rol(es) para ${user.firstName}.`); onDone(); }
    catch (e) { toast.error('Error', (e as Error).message); }
  };
  return (
    <Modal title={`Asignar roles · ${user.firstName} ${user.lastName}`} subtitle="Seleccione los roles que tendrá este usuario." onClose={onClose}
      footer={<><span className="muted small grow">{sel.length} rol(es)</span><button className="btn btn-ghost" onClick={onClose}>Cancelar</button><button className="btn btn-primary" onClick={save}>Guardar</button></>}>
      <div className="grid" style={{ gap: 10 }}>
        {roles.map((r) => {
          const checked = sel.includes(r.id);
          return (
            <label key={r.id} className={`check-card ${checked ? 'checked' : ''}`}>
              <input type="checkbox" checked={checked} onChange={() => setSel(checked ? sel.filter((x) => x !== r.id) : [...sel, r.id])} />
              <span className="icon-tile" style={{ width: 30, height: 30, background: r.color }}>{r.isAdmin ? <IconShield width={14} height={14} /> : <IconRoles width={14} height={14} />}</span>
              <div className="grow"><div className="cc-title">{r.name} {r.isAdmin && <span className="badge badge-red">Acceso completo</span>}</div><div className="cc-desc">{r.description}</div></div>
            </label>
          );
        })}
      </div>
    </Modal>
  );
}
